name: Node.js CI

on:
  pull_request:
    branches: [ "develop" ]

permissions:
      id-token: write
      contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Yarn
      run: npm install -g yarn

    - run: yarn install

    - name: Generate OpenAPI Documentation
      run: yarn docusaurus gen-api-docs all

    - run: yarn run build

    - name: Uninstall Yarn
      if: always()
      run: npm uninstall -g yarn

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: OIDCSession

    - name: Copy files to staging S3 bucket
      run: |
        aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}

    - name: Invalidate CloudFront Stale Distribution
      run: |
        distribution_id=$(aws cloudfront list-distributions --query "DistributionList.Items[?Origins.Items[?DomainName=='${{ secrets.AWS_S3_BUCKET_NAME }}.s3.us-east-1.amazonaws.com']].Id" --output text)
         
        echo "CloudFront Distribution ID: $distribution_id"
        aws cloudfront create-invalidation --distribution-id $distribution_id --paths "/*"
        echo "Invalidation Started For CloudFront Distribution ID: $distribution_id"
