name: Node.js CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Yarn
      run: npm install -g yarn

    - run: yarn install

    - name: Generate OpenAPI Documentation
      run: yarn docusaurus gen-api-docs all

    - run: yarn run build

    - name: Uninstall Yarn
      if: always()
      run: npm uninstall -g yarn

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
        aws-region: us-east-1
    - name: Copy files to staging S3 bucket
      run: |
        aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}
